"""Build a reproducible train/val/test split for a single country's data, from manifest.csv
(roadmap: infra-defect-detection, phase 2 - CNN baseline).

Why a separate script rather than letting Ultralytics auto-split: phase 2's whole point is to
establish a "same-country train/test" baseline number that phase 3 later compares a cross-country
number against - that comparison is only meaningful if the split is fixed, recorded, and re-usable
(so phase 3's report can say "the same Czech test set" rather than "some random subset"). Ultralytics
can auto-split a folder, but doesn't write out a reproducible, inspectable record of which images
ended up in which split - so we do it ourselves and hand Ultralytics explicit image-list .txt files.

Usage:
    python scripts/make_country_split.py --country Czech
    python scripts/make_country_split.py --country Czech --train-frac 0.7 --val-frac 0.15 --seed 42
"""
import argparse
import csv
import json
import random
import sys
from pathlib import Path

DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent / "data"

CLASS_NAMES = ["longitudinal_crack", "transverse_crack", "alligator_crack", "pothole"]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--country", required=True, help="country name as it appears in manifest.csv's country column")
    parser.add_argument("--data-dir", default=str(DEFAULT_DATA_DIR))
    parser.add_argument("--train-frac", type=float, default=0.7)
    parser.add_argument("--val-frac", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=42, help="fixed shuffle seed - record this alongside any reported metric")
    args = parser.parse_args(argv)

    if args.train_frac + args.val_frac >= 1.0:
        print(f"--train-frac ({args.train_frac}) + --val-frac ({args.val_frac}) must leave room for a "
              f"non-empty test split (currently sums to {args.train_frac + args.val_frac})", file=sys.stderr)
        return 1

    data_dir = Path(args.data_dir)
    manifest_path = data_dir / "manifest.csv"
    if not manifest_path.exists():
        print(f"{manifest_path} not found - run extract_convert_per_country.py first.", file=sys.stderr)
        return 1

    with open(manifest_path, newline="") as f:
        rows = [r for r in csv.DictReader(f) if r["country"] == args.country]

    if not rows:
        print(f"No rows for country={args.country!r} in {manifest_path} - check spelling, or that "
              f"extract_convert_per_country.py was run with --countries {args.country}.", file=sys.stderr)
        return 1

    # Sort first so the shuffle is deterministic regardless of manifest.csv's row order (which
    # itself depends on filesystem iteration order and isn't guaranteed stable across re-runs).
    rows.sort(key=lambda r: r["image"])
    rng = random.Random(args.seed)
    rng.shuffle(rows)

    n = len(rows)
    n_train = int(n * args.train_frac)
    n_val = int(n * args.val_frac)
    splits = {
        "train": rows[:n_train],
        "val": rows[n_train:n_train + n_val],
        "test": rows[n_train + n_val:],
    }

    split_dir = data_dir / "splits" / args.country
    split_dir.mkdir(parents=True, exist_ok=True)

    for split_name, split_rows in splits.items():
        list_path = split_dir / f"{split_name}.txt"
        with open(list_path, "w") as f:
            for r in split_rows:
                # manifest.csv's "image" column is already relative to data_dir (e.g.
                # "processed/Czech/images/Czech__xxx.jpg") - Ultralytics wants absolute paths to be
                # safe regardless of what directory `yolo train` is invoked from.
                f.write(str((data_dir / r["image"]).resolve()) + "\n")
        print(f"  {split_name}: {len(split_rows)} images -> {list_path}")

    if any(len(v) == 0 for v in splits.values()):
        print(f"\nWARNING: at least one split is empty (train={len(splits['train'])}, "
              f"val={len(splits['val'])}, test={len(splits['test'])}) - {args.country} may not have "
              f"enough images for these fractions.", file=sys.stderr)

    dataset_yaml_path = split_dir / "dataset.yaml"
    dataset_yaml_path.write_text(
        f"# Auto-generated by make_country_split.py for country={args.country}, seed={args.seed}.\n"
        f"# Labels are found by Ultralytics' convention: same path with the LAST 'images' path "
        f"component replaced by 'labels' and the extension replaced by .txt - this matches how "
        f"convert_voc_to_yolo.py laid out data/processed/{args.country}/images/ + labels/.\n"
        f"train: {(split_dir / 'train.txt').resolve()}\n"
        f"val: {(split_dir / 'val.txt').resolve()}\n"
        f"test: {(split_dir / 'test.txt').resolve()}\n"
        f"nc: {len(CLASS_NAMES)}\n"
        f"names: {CLASS_NAMES}\n"
    )
    print(f"  dataset.yaml -> {dataset_yaml_path}")

    split_config = {
        "country": args.country,
        "seed": args.seed,
        "train_frac": args.train_frac,
        "val_frac": args.val_frac,
        "test_frac": round(1.0 - args.train_frac - args.val_frac, 6),
        "n_total": n,
        "n_train": len(splits["train"]),
        "n_val": len(splits["val"]),
        "n_test": len(splits["test"]),
    }
    config_path = split_dir / "split_config.json"
    config_path.write_text(json.dumps(split_config, indent=2) + "\n")
    print(f"  split_config.json -> {config_path}")
    print(f"\n{args.country}: {n} total images -> train={len(splits['train'])} "
          f"val={len(splits['val'])} test={len(splits['test'])} (seed={args.seed})")
    print(f"\nNext: python scripts/train_cnn_baseline.py --data {dataset_yaml_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
